In [1]:
import numpy as np
import pandas as pd
import time

import sklearn.metrics as metrics
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import to_categorical
from keras import models
from keras import layers

In [2]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

In [3]:
X = np.arange(10).reshape(-1, 1)
y = np.array([0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])
y = to_categorical(y)

In [4]:
print(X)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [5]:
model = models.Sequential()
model.add(layers.Dense(10,kernel_initializer='RandomNormal', activation='relu'))
model.add(layers.Dense(2,activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [11]:
t0 = time.time()
history = model.fit(X, y, epochs=50)
t1 = time.time()
dt = (t1 - t0)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 1.0000 - loss: 0.1976
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 1.0000 - loss: 0.1968
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 1.0000 - loss: 0.1963
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 1.0000 - loss: 0.1959
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 1.0000 - loss: 0.1955
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 1.0000 - loss: 0.1952
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.1949
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.1946
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.1943
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 1.0000 - loss: 0.1941
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.1938
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - accuracy: 1.0000 - loss: 0.1936


In [7]:
#model.save('model_cat_weights.keras')
#history_df=pd.DataFrame(history.history)
#history_df.to_excel('model_cat_history.xlsx')
history_df=pd.read_excel('model_cat_history.xlsx', index_col=0)
model = models.load_model('model_cat_weights.keras')

In [8]:
history_df

accuracy      loss
0         0.7  0.640281
1         0.6  0.638777
2         0.6  0.637289
3         0.6  0.635816
4         0.6  0.634358
..        ...       ...
995       1.0  0.198260
996       1.0  0.198118
997       1.0  0.197976
998       1.0  0.197835
999       1.0  0.197693

[1000 rows x 2 columns]

In [9]:
import holoviews as hv
import panel as pn
import hvplot
import hvplot.pandas
hv.extension('bokeh')

In [10]:
history_df.hvplot.line( x='index',   
                  line_width=3,  xlim=(0, 1000),
                  legend='top',   widget_location='left',
                  grid = True, xlabel='Эпоха обучения', ylabel='Значение',
                  height=400, width=700)

HoloViews(NdOverlay, height=400, sizing_mode='fixed', widget_location='left', width=700)

In [12]:
z = model.predict(X)
z

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step


array([[8.97738993e-01, 1.02260955e-01],
       [8.97738993e-01, 1.02260955e-01],
       [8.97738993e-01, 1.02260955e-01],
       [5.62751651e-01, 4.37248349e-01],
       [7.65519440e-02, 9.23448086e-01],
       [5.31112216e-03, 9.94688869e-01],
       [3.43799271e-04, 9.99656200e-01],
       [2.21513437e-05, 9.99977827e-01],
       [1.42680233e-06, 9.99998569e-01],
       [9.19007448e-08, 9.99999881e-01]], dtype=float32)

In [13]:
res_df=pd.DataFrame({'X': X[:,0], 'Y_train':y[:,1], 'Y_pred': z[:,1]})
res_df

X  Y_train    Y_pred
0  0      0.0  0.102261
1  1      0.0  0.102261
2  2      0.0  0.102261
3  3      0.0  0.437248
4  4      1.0  0.923448
5  5      1.0  0.994689
6  6      1.0  0.999656
7  7      1.0  0.999978
8  8      1.0  0.999999
9  9      1.0  1.000000

In [14]:
res_df=pd.DataFrame({'X': X[:,0], 'Y_train':y[:,1], 'Y_pred': z[:,1]})
p1=res_df.hvplot.scatter( x='X',  marker='circle', size=150, alpha=0.75, legend='top' )
p2=res_df.hvplot.line( x='X',  y=['Y_pred'],  line_width=3, line_dash='dashed', legend='top')
(p2 * p1).opts(title='Обучение: Класс 1', show_grid = True, xlabel='X', ylabel='Y', height=400, width=700)

:Overlay
   .Curve.I     :Curve   [X]   (Y_pred)
   .NdOverlay.I :NdOverlay   [Variable]
      :Scatter   [X]   (value)

In [31]:
plot_w=[]
for i,layer in enumerate(model.layers):
    weights = layer.get_weights()[0]
    shape = weights.shape
    plot_w.append( hv.Raster(weights).opts(title ='Слой %i' %(i), cmap='hot',colorbar=True, show_frame=True, xaxis=False, yaxis=False, height=300, width=300))
layout=hv.Layout(plot_w)
layout.opts( title ="Веса", width=600, height=500)

:Layout
   .Raster.I  :Raster   [x,y]   (z)
   .Raster.II :Raster   [x,y]   (z)

In [23]:
model = models.Sequential()
model.add(layers.Dense(2,kernel_initializer='RandomNormal', activation='sigmoid'))
model.add(layers.Dense(2,activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer=keras.optimizers.Nadam(learning_rate=0.02), metrics=['accuracy'])

In [24]:
history = model.fit(X, y, epochs=150)

Epoch 1/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.4000 - loss: 0.7604
Epoch 2/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.7450
Epoch 3/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4000 - loss: 0.7355
Epoch 4/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - accuracy: 0.4000 - loss: 0.7276
Epoch 5/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4000 - loss: 0.7204
Epoch 6/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.4000 - loss: 0.7138
Epoch 7/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.4000 - loss: 0.7077
Epoch 8/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.4000 - loss: 0.7019
Epoch 9/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6964
Epoch 10/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.7000 - loss: 0.6913
Epoch 11/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8000 - loss: 0.6866
Epoch 12/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.9000 - l

In [25]:
pd.DataFrame(history.history).hvplot.line( x='index',   
                  line_width=3,  
                  legend='top',   widget_location='left',
                  grid = True, xlabel='Эпоха обучения', ylabel='Значение',
                  height=400, width=700)

HoloViews(NdOverlay, height=400, sizing_mode='fixed', widget_location='left', width=700)

In [26]:
z = model.predict(X)
z

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step


array([[0.97791654, 0.02208346],
       [0.9527059 , 0.0472941 ],
       [0.8719428 , 0.12805715],
       [0.6485318 , 0.35146818],
       [0.3260964 , 0.67390364],
       [0.1321238 , 0.8678762 ],
       [0.06089772, 0.9391023 ],
       [0.03584141, 0.9641586 ],
       [0.02594314, 0.9740569 ],
       [0.02155639, 0.9784436 ]], dtype=float32)

In [29]:
model.evaluate(X, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.8000 - loss: 0.4108


[0.41080600023269653, 0.800000011920929]

In [30]:
res_df=pd.DataFrame({'X': X[:,0], 'Y_train':y[:,1], 'Y_pred': z[:,1]})
p1=res_df.hvplot.scatter( x='X',  marker='circle', size=150, alpha=0.75, legend='top' )
p2=res_df.hvplot.line( x='X',  y=['Y_pred'],  line_width=3, line_dash='dashed', legend='top')
(p2 * p1).opts(title='Обучение NN2: Класс 1', show_grid = True, xlabel='X', ylabel='Y', height=400, width=700)

:Overlay
   .Curve.I     :Curve   [X]   (Y_pred)
   .NdOverlay.I :NdOverlay   [Variable]
      :Scatter   [X]   (value)

In [22]:
X = np.arange(10).reshape(-1, 1)
y = np.array([0., 0., 1., 0., 0., 1., 1., 1., 1., 1.])
y = to_categorical(y)